name: Setup node
description: Sets up node, npm and installs repository dependencies

runs:
    using: 'composite'

    steps:
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
              node-version: 16.x
              cache: 'npm'
              cache-dependency-path: package-lock.json

        - run: npm ci
