[build]
    base = "./"
    publish = "dist/apps/rockket-web"
    command = "npx nx build rockket-web"

[[plugins]]
    package = "@netlify/plugin-lighthouse"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.deploy-preview.build]
    ignore = "bash ../scripts/check-dependencies-label-for-pr.sh $REVIEW_ID"