[build]
    base = "./"
    publish = "dist/apps/rockket-web"
    command = "npx nx run rockket-web:build:production"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[context.deploy-preview.build]
    ignore = "bash ./scripts/check-dependencies-label-for-pr.sh $REVIEW_ID"